import { serverTimestamp } from "firebase/firestore";

const DataEpisode = [
  // {
  //   title: "5 Minutes Trailer",
  //   video_id: "6SGdLQObVzdxhBr4KAah",
  //   type: "Trailer",
  //   season: 1,
  //   episode_num: 1,
  //   description: `The story is set in the 15th century Kingdom of P. Rafał, a child prodigy, is allowed to skip a grade and enter university. In response to the expectations of those around him, he declares that he will major in theology, which was considered the most important subject at the time. However, he is unable to abandon his passion for astronomy, which he has been passionate about for a long time. One day, he meets a mysterious scholar named Hubert. Hubert was tortured and imprisoned for touching upon a taboo based on heretical thought. The scholar he was researching was a shocking "hypothesis" about the universe.`,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://img.youtube.com/vi/yBVJEJOK6tA/sddefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "yBVJEJOK6tA",
  //   video_url: "https://files.catbox.moe/pvgrbu.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `Frieren: Beyond Journey's End" Trailer Vol.3`,
  //   video_id: "4zBualqdneIK1yoSenFk",
  //   type: "Trailer",
  //   season: 1,
  //   episode_num: 1,
  //   description: `Trailer Vol.3! `,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/tR8YH0G67Rk/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "tR8YH0G67Rk",
  //   video_url: "https://files.catbox.moe/zym3vv.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `TVアニメ『BLEACH 千年血戦篇』PV第4弾`,
  //   video_id: "DyfSFoE56RcHW6CukPIk",
  //   type: "Trailer",
  //   season: 1,
  //   episode_num: 1,
  //   description: `2024年10月テレ東系列ほかにて放送開始。`,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/tShYCQALuH8/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "tShYCQALuH8",
  //   video_url: "https://files.catbox.moe/qzqp61.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `Re:ゼロから始める異世界生活`,
  //   video_id: "GAPG8Y7kqCMhtK5oeLa8",
  //   type: "Trailer",
  //   season: 1,
  //   episode_num: 1,
  //   description: `TVアニメ「Re:ゼロから始める異世界生活」3rd season`,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/qMJNdQFPaHk/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "qMJNdQFPaHk",
  //   video_url: "https://files.catbox.moe/h58w2e.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `かぐや様は告らせたい-ウルトラロマンティック-`,
  //   video_id: "GD4KVMg8l5QBBUOJxHC0",
  //   type: "Trailer",
  //   season: 1,
  //   episode_num: 1,
  //   description: `TVアニメ『かぐや様は告らせたい-ウルトラロマンティック-』オープニング映像を期間限定公開！`,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/j3p6sXq_uUM/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "j3p6sXq_uUM",
  //   video_url: "https://files.catbox.moe/x4q93l.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `March Lion PV`,
  //   video_id: "IPs6SrpciOLFOgcZkb4W",
  //   type: "PV",
  //   season: 1,
  //   episode_num: 1,
  //   description: ``,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/w7E_J4AWQtc/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "w7E_J4AWQtc",
  //   video_url: "https://files.catbox.moe/bccspk.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `Fruits Basket PV`,
  //   video_id: "IxJzuMHy3tAFLceTMeX1",
  //   type: "PV",
  //   season: 1,
  //   episode_num: 1,
  //   description: ``,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/ci2XSskC_wA/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "ci2XSskC_wA",
  //   video_url: "https://files.catbox.moe/qka0u3.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `鋼の錬金術師 PV3`,
  //   video_id: "TA69GjZdEfJNiL3X34tU",
  //   type: "PV",
  //   season: 1,
  //   episode_num: 1,
  //   description: `7月2日に公開される劇場版アニメ「鋼の錬金術師嘆きの丘（ミロス）の聖なる星」のPV第3弾が5月20日、公開された。ストーリーの紹介を含め、エドとアルの戦闘シーンなど劇場版の見どころを紹介している。`,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/M1MECOw1H60/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "M1MECOw1H60",
  //   video_url: "https://files.catbox.moe/eavjvy.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `HUNTER x HUNTER promotional video`,
  //   video_id: "ZVCoUvmQ78ZXDVxhZorw",
  //   type: "PV",
  //   season: 1,
  //   episode_num: 1,
  //   description: `『幽☆遊☆白書』『レベルE』『HUNTER×HUNTER』等、名作原画一挙公開！`,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/bfv-VaaAlxc/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "bfv-VaaAlxc",
  //   video_url: "https://files.catbox.moe/5ldy59.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `TVアニメ「進撃の巨人」The Final Season　PV`,
  //   video_id: "hpyxljToabRumGuRvxFh",
  //   type: "PV",
  //   season: 1,
  //   episode_num: 1,
  //   description: `TVアニメ「進撃の巨人」The Final Season`,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/SlNpRThS9t8/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "SlNpRThS9t8",
  //   video_url: "https://files.catbox.moe/7m68hi.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `Koe no Katachi PV`,
  //   video_id: "lTbo48lWMFCP4XFQ2uri",
  //   type: "PV",
  //   season: 1,
  //   episode_num: 1,
  //   description: `ガキ大将だった小学6年生の石田将也は、転校生の少女、西宮硝子へ無邪気な好奇心を持つ。​「いい奴ぶってんじゃねーよ。」​`,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/U0qfxpI_Vps/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "U0qfxpI_Vps",
  //   video_url: "https://files.catbox.moe/mfaule.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `CLANNAD 〜AFTER STORY〜 Episode 18 Scene`,
  //   video_id: "tgonm7xUoBXL46yntU6T",
  //   type: "Main Story",
  //   season: 1,
  //   episode_num: 1,
  //   description: `​`,
  //   duration: 300,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/6u6niCF-tD0/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "6u6niCF-tD0",
  //   video_url: "https://files.catbox.moe/3rlkdh.mp4",
  //   views_count: 80000,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  // {
  //   title: `Steins;Gate | Anime Trailer [HD] | 2011`,
  //   video_id: "lJr5vx1mTclItY3SbGxR",
  //   type: "Trailer",
  //   season: 1,
  //   episode_num: 1,
  //   description: `In Steins;Gate, self-proclaimed mad scientist Rintarou Okabe rents out a room in a rickety old building in Akihabara, where he indulges himself in his hobby of inventing prospective "future gadgets" with fellow lab members: Mayuri Shiina, his air-headed childhood friend, and Hashida Itaru, a perverted hacker nicknamed "Daru." The three pass the time by tinkering with their most promising contraption yet, a machine dubbed the "Phone Microwave," which performs the strange function of morphing bananas into piles of green gel.​`,
  //   duration: 171,
  //   privacy_status: "public",
  //   thumbnail_url: "https://i.ytimg.com/vi/uMYhjVwp0Fk/maxresdefault.jpg",
  //   last_modified_date: serverTimestamp(),
  //   upload_date: serverTimestamp(),
  //   episode_id: "uMYhjVwp0Fk",
  //   video_url: "https://files.catbox.moe/4df6j3.mp4",
  //   views_count: 1247428,
  //   like_count: 102,
  //   dislikes_count: 0,
  // },
  {
    title: `BLEACH (2024)_ Thousand-Year Blood War Pt. 3「AMV」Clarity`,
    video_id: "DyfSFoE56RcHW6CukPIk",
    type: "AMV",
    season: 1,
    episode_num: 1,
    description: `​`,
    duration: 180,
    privacy_status: "public",
    thumbnail_url: "https://i.ytimg.com/vi/e5nip41FtA8/maxresdefault.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    episode_id: "e5nip41FtA8",
    video_url: "https://files.catbox.moe/u1p9im.mp4",
    views_count: 1247428,
    like_count: 102,
    dislikes_count: 0,
  },
];

export default DataEpisode;
