import { serverTimestamp } from "firebase/firestore";

const Database = [
  {
    title: "Re:Zero kara Hajimeru Isekai Seikatsu 3rd Season",
    jp_title: "Re:ゼロから始める異世界生活",
    studios: ["White Fox"],
    category_id: 1,
    type: 1,
    description: "Third season of Re:Zero kara Hajimeru Isekai Seikatsu.",
    duration: 1500,
    privacy_status: "public",
    tags: ["Drama", "Fantasy", "Suspense"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/1250/137317.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/1317/134750.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    views_count: 80000,
    like_count: 102,
    dislikes_count: 0,
  },
  {
    title: "Sousou no Frieren",
    jp_title: "葬送のフリーレン",
    studios: ["Madhouse"],
    category_id: 1,
    type: 2,
    description: `During their decade-long quest to defeat the Demon King, the members of the hero's party—Himmel himself, the priest Heiter, the dwarf warrior Eisen, and the elven mage Frieren—forge bonds through adventures and battles, creating unforgettable precious memories for most of them.

However, the time that Frieren spends with her comrades is equivalent to merely a fraction of her life, which has lasted over a thousand years. When the party disbands after their victory, Frieren casually returns to her "usual" routine of collecting spells across the continent. Due to her different sense of time, she seemingly holds no strong feelings toward the experiences she went through.

As the years pass, Frieren gradually realizes how her days in the hero's party truly impacted her. Witnessing the deaths of two of her former companions, Frieren begins to regret having taken their presence for granted; she vows to better understand humans and create real personal connections. Although the story of that once memorable journey has long ended, a new tale is about to begin.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Adventure", "Drama", "Fantasy"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video02",
    video_url: "video02",
    views_count: 380000,
    like_count: 140,
    dislikes_count: 0,
  },
  {
    title: "One Piece Fan Letter",
    jp_title: "ONE PIECE FAN LETTER",
    studios: ["Madhouse"],
    category_id: 1,
    type: 2,
    description: `Two years after the Summit War in which Straw Hat pirate Luffy lost his brother Ace, the story takes place on the Sabaody Archipelago. The protagonist, a young girl who has a strong admiration for Nami, sets off on a small adventure. This is an ensemble drama that focuses on people who do not "pursue" ONE PIECE, depicting the reunion of the Straw Hat Pirates from their perspective.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Action", "Adventure", "Fantasy"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/1455/146229.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/1455/146229.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video03",
    video_url: "video03",
    views_count: 804000,
    like_count: 102,
    dislikes_count: 0,
  },
  {
    title: "Fullmetal Alchemist: Brotherhood",
    jp_title: "鋼の錬金術師 FULLMETAL ALCHEMIST",
    studios: ["Bones"],
    category_id: 1,
    type: 2,
    description: `After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality. Ignoring the alchemical principle banning human transmutation, the boys attempted to bring their recently deceased mother back to life. Instead, they suffered brutal personal loss: Alphonse's body disintegrated while Edward lost a leg and then sacrificed an arm to keep Alphonse's soul in the physical realm by binding it to a hulking suit of armor.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Action", "Adventure", "Drama", "Fantasy"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/1629/108486.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/1629/108486.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video04",
    video_url: "video04",
    views_count: 800002,
    like_count: 102,
    dislikes_count: 0,
  },
  {
    title: "Steins;Gate",
    jp_title: "STEINS;GATE",
    studios: ["White Fox"],
    category_id: 1,
    type: 2,
    description: `Eccentric scientist Rintarou Okabe has a never-ending thirst for scientific exploration. Together with his ditzy but well-meaning friend Mayuri Shiina and his roommate Itaru Hashida, Okabe founds the Future Gadget Laboratory in the hopes of creating technological innovations that baffle the human psyche. Despite claims of grandeur, the only notable "gadget" the trio have created is a microwave that has the mystifying power to turn bananas into green goo.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Drama", "Sci-Fi", "Suspense"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/8/35137.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/8/35137.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video05",
    video_url: "video05",
    views_count: 840000,
    like_count: 102,
    dislikes_count: 0,
  },
  {
    title: "Shingeki no Kyojin",
    jp_title: "進撃の巨人",
    studios: ["Wit Studio"],
    category_id: 1,
    type: 1,
    description: `Returning to the tattered Shiganshina District that was once his home, Eren Yeager and the Corps find the town oddly unoccupied by Titans. Even after the outer gate is plugged, they strangely encounter no opposition. The mission progresses smoothly until Armin Arlert, highly suspicious of the enemy's absence, discovers distressing signs of a potential scheme against them.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Action", "Drama", "Suspense"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/1220/106899.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/1220/106899.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video06",
    video_url: "video06",
    views_count: 142,
    like_count: 42,
    dislikes_count: 0,
  },
  {
    title: "Gintama",
    jp_title: "銀魂",
    studios: ["Bandai Namco Pictures"],
    category_id: 1,
    type: 1,
    description: `Gintoki, Shinpachi, and Kagura return as the fun-loving but broke members of the Yorozuya team! Living in an alternate-reality Edo, where swords are prohibited and alien overlords have conquered Japan, they try to thrive on doing whatever work they can get their hands on. However, Shinpachi and Kagura still haven't been paid... Does Gin-chan really spend all that cash playing pachinko?`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Action", "Comedy", "Sci-Fi"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/11/78166.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/11/78166.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video07",
    video_url: "video07",
    views_count: 180000,
    like_count: 120,
    dislikes_count: 0,
  },
  {
    title: "Hunter x Hunter",
    jp_title: "ハンター×ハンター",
    studios: ["Madhouse"],
    category_id: 1,
    type: 1,
    description: `Hunters devote themselves to accomplishing hazardous tasks, all from traversing the world's uncharted territories to locating rare items and monsters. Before becoming a Hunter, one must pass the Hunter Examination—a high-risk selection process in which most applicants end up handicapped or worse, deceased.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Action", "Adventure", "Fantasy"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/13/47129.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/13/47129.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video08",
    video_url: "video08",
    views_count: 800000,
    like_count: 102,
    dislikes_count: 0,
  },
  {
    title: "Bleach",
    jp_title: "BLEACH 千年血戦篇",
    studios: ["Pierrot"],
    category_id: 1,
    type: 1,
    description: `Substitute Soul Reaper Ichigo Kurosaki spends his days fighting against Hollows, dangerous evil spirits that threaten Karakura Town. Ichigo carries out his quest with his closest allies: Orihime Inoue, his childhood friend with a talent for healing; Yasutora Sado, his high school classmate with superhuman strength; and Uryuu Ishida, Ichigo's Quincy rival.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Action", "Adventure", "Supernatural"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/1785/106505.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/1908/135431.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video09",
    video_url: "video09",
    views_count: 80500,
    like_count: 5000,
    dislikes_count: 0,
  },
  {
    title: "Kaguya-sama wa Kokurasetai: Ultra Romantic",
    jp_title: "かぐや様は告らせたい-ウルトラロマンティック-",
    studios: ["A-1 Pictures"],
    category_id: 1,
    type: 1,
    description: `The elite members of Shuchiin Academy's student council continue their competitive day-to-day antics. Council president Miyuki Shirogane clashes daily against vice-president Kaguya Shinomiya, each fighting tooth and nail to trick the other into confessing their romantic love. Kaguya struggles within the strict confines of her wealthy, uptight family, rebelling against her cold default demeanor as she warms to Shirogane and the rest of her friends.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Comedy", "Romance"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/1430/118919.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/1430/118919.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video10",
    video_url: "video10",
    views_count: 500000,
    like_count: 2000,
    dislikes_count: 0,
  },
  {
    title: "Fruits Basket",
    jp_title: "フルーツバスケット The Final",
    studios: ["TMS Entertainment"],
    category_id: 1,
    type: 1,
    description: `Hundreds of years ago, the Chinese zodiac spirits and their god swore to stay together eternally. United by this promise, the possessed members of the Souma family shall always return to each other under any circumstances. Yet, when these bonds shackle them from freedom, it becomes an undesirable burden—a curse. As head of the clan, Akito is convinced that he shares a special connection with the other Soumas. While he desperately clings to this fantasy, the rest of the family remains isolated and suppressed by the fear of punishment.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Drama", "Romance", "Supernatural"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/1081/111338.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/1081/111338.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    views_count: 50000,
    like_count: 10,
    dislikes_count: 0,
  },
  {
    title: "Clannad",
    jp_title: "クラナド",
    studios: ["Kyoto Animation"],
    category_id: 1,
    type: 1,
    description: `Tomoya Okazaki and Nagisa Furukawa have graduated from high school, and together, they experience the emotional rollercoaster of growing up. Unable to decide on a course for his future, Tomoya learns the value of a strong work ethic and discovers the strength of Nagisa's support. Through the couple's dedication and unity of purpose, they push forward to confront their personal problems, deepen their old relationships, and create new bonds.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Drama", "Romance", "Supernatural"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/13/12292.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/13/12292.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video12",
    video_url: "video12",
    views_count: 10000,
    like_count: 10,
    dislikes_count: 0,
  },
  {
    title: "A Silent Voice",
    jp_title: "聲の形",
    studios: ["Kyoto Animation"],
    category_id: 1,
    type: 1,
    description: `Tomoya Okazaki and Nagisa Furukawa have graduated from high school, and together, they experience the emotional rollercoaster of growing up. Unable to decide on a course for his future, Tomoya learns the value of a strong work ethic and discovers the strength of Nagisa's support. Through the couple's dedication and unity of purpose, they push forward to confront their personal problems, deepen their old relationships, and create new bonds.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Award Winning", "Drama"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/1254/109618.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/1254/109618.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video13",
    video_url: "video13",
    views_count: 80000,
    like_count: 10,
    dislikes_count: 0,
  },
  {
    title: "March Comes In Like a Lion",
    jp_title: "3月のライオン",
    studios: ["Shaft"],
    category_id: 1,
    type: 1,
    description: `Now in his second year of high school, Rei Kiriyama continues pushing through his struggles in the professional shogi world as well as his personal life. Surrounded by vibrant personalities at the shogi hall, the school club, and in the local community, his solitary shell slowly begins to crack. Among them are the three Kawamoto sisters—Akari, Hinata, and Momo—who forge an affectionate and familial bond with Rei. Through these ties, he realizes that everyone is burdened by their own emotional hardships and begins learning how to rely on others while supporting them in return.`,
    duration: 1500,
    privacy_status: "public",
    tags: ["Drama"],
    thumbnail_horizontal_url:
      "https://cdn.myanimelist.net/images/anime/1429/100628.jpg",
    thumbnail_vertical_url:
      "https://cdn.myanimelist.net/images/anime/1429/100628.jpg",
    last_modified_date: serverTimestamp(),
    upload_date: serverTimestamp(),
    video_id: "video14",
    video_url: "video14",
    views_count: 1000000,
    like_count: 10,
    dislikes_count: 0,
  },
];

export default Database;
